const provinces = [
  {
    name: 'Punjab',
    logo: '/logo/punjab.png',
    link: 'https://www.punjab.gov.pk/',
    capital: 'Lahore',
    population: '127.7 Million',
    populationPercent: '52.9%',
    area: '205,344 km²',
    density: '622 per km²',
    urbanization: '36.4%',
    majorCities: ['Lahore', 'Faisalabad', 'Rawalpindi', 'Multan', 'Gujranwala'],
    established: '1947',
    description: 'Most populous province, agricultural heartland',
    color: 'emerald',
    highlights: ['Largest population', 'Agricultural hub', 'Industrial center']
  },
  {
    name: 'Sindh',
    logo: '/logo/sindh.png',
    link: 'https://www.sindh.gov.pk/',
    capital: 'Karachi',
    population: '55.7 Million',
    populationPercent: '23.1%',
    area: '140,914 km²',
    density: '395 per km²',
    urbanization: '54.0%',
    majorCities: ['Karachi', 'Hyderabad', 'Sukkur', 'Larkana', 'Nawabshah'],
    established: '1947',
    description: 'Economic powerhouse, most urbanized province',
    color: 'blue',
    highlights: ['Financial hub', 'Highest urbanization', 'Port access']
  },
  {
    name: 'Khyber Pakhtunkhwa',
    logo: '/logo/kpk.png',
    link: 'https://kp.gov.pk/',
    capital: 'Peshawar',
    population: '40.9 Million',
    populationPercent: '16.9%',
    area: '101,741 km²',
    density: '402 per km²',
    urbanization: '18.8%',
    majorCities: ['Peshawar', 'Mardan', 'Mingora', 'Kohat', 'Bannu'],
    established: '1901 (NWFP), 2010 (renamed)',
    description: 'Northwestern frontier, rich cultural heritage',
    color: 'orange',
    highlights: ['Cultural diversity', 'Historic region', 'Strategic location']
  },
  {
    name: 'Balochistan',
    logo: '/logo/baluch.png',
    link: 'https://balochistan.gov.pk/',
    capital: 'Quetta',
    population: '14.9 Million',
    populationPercent: '6.2%',
    area: '347,190 km²',
    density: '43 per km²',
    urbanization: '27.5%',
    majorCities: ['Quetta', 'Gwadar', 'Turbat', 'Khuzdar', 'Sibi'],
    established: '1947',
    description: 'Largest by area, rich in natural resources',
    color: 'red',
    highlights: ['Largest province', 'Natural resources', 'CPEC gateway']
  },
  {
    name: 'Islamabad Capital Territory',
    logo: '/logo.png',
    link: '/provinces/islamabad',
    capital: 'Islamabad',
    population: '2.4 Million',
    populationPercent: '1.0%',
    area: '906 km²',
    density: '2,648 per km²',
    urbanization: '100%',
    majorCities: ['Islamabad', 'Rawalpindi (adjacent)'],
    established: '1960',
    description: 'Federal capital, planned city',
    color: 'green',
    highlights: ['Federal capital', 'Planned city', 'Government center']
  },
  {
    name: 'Gilgit-Baltistan',
    logo: '/logo/gilgit.png',
    link: 'https://gilgitbaltistan.gov.pk/',
    capital: 'Gilgit',
    population: '1.5 Million',
    populationPercent: '0.6%',
    area: '72,971 km²',
    density: '21 per km²',
    urbanization: '16.2%',
    majorCities: ['Gilgit', 'Skardu', 'Hunza', 'Ghanche'],
    established: '1947 (Northern Areas), 2009 (GB)',
    description: 'Northern territories, mountainous region',
    color: 'indigo',
    highlights: ['Mountain tourism', 'Strategic location', 'Natural beauty']
  },
  {
    name: 'Azad Jammu & Kashmir',
    logo: '/logo/ajk.png',
    link: 'https://ajk.gov.pk/',
    capital: 'Muzaffarabad',
    population: '4.0 Million',
    populationPercent: '1.7%',
    area: '13,297 km²',
    density: '304 per km²',
    urbanization: '15.2%',
    majorCities: ['Muzaffarabad', 'Mirpur', 'Kotli', 'Rawalakot'],
    established: '1947',
    description: 'Administered territory, scenic valleys',
    color: 'purple',
    highlights: ['Autonomous region', 'Scenic beauty', 'Diaspora connections']
  },
];
console.log(provinces);